### ISSUE TITLE
Remove the concept of Well Known Scale Sets

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-code-sprint-2021-05#38]
**Day 3 of the 2021-05 Sprint**

The sprint participants pointed out that the concept of a WKSS appears to duplicate the same information that is in the Tile Matrix Set(TMS). As a result a WKSS is not particularly useful. There was a recommendation that the new version of the TMS standard should remove the concept of a TMS.

**Comment by jerstlouis** [comment]
We previously discussed this at length in the SWG ( https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/24 ) and agreed to make the concept obsolete, but to keep it to facilitate compatibility with and transition from WMTS implementations.

The concept is optional in the definition of a TileMatrixSet, and we don't expect new WKSS to be defined, unless required to facilitate compatibility with WMTS implementations.

**Comment by cportele** [comment]
I wouldn't call the discussion in the issue "discussed at length" 😁

The point was mainly that the WKSS topic takes quite some room in the document, adds no value, adds nothing normative and is just confusing to most readers (including me). If it is text for developers "migrating" from WMTS, maybe the WKSS discussion should be moved to the informative guide?

**Comment by jerstlouis** [comment]
@cportele you're right the issue is short on comments, but there was additional discussions during the meetings as well which is not reflected there. 

There is a small section as part the conceptual description of TileMatrix Set ( https://docs.opengeospatial.org/DRAFTS/17-083r3.html#well-known-scale-sets ).

And the informative Annex C describing those WKSS.

The `wellKnownScale` set is still an optional field as part of a TileMatrixSet definition and normative schemas.

If there isn't already, maybe there _should_ be normative requirements that if a TileMatrixSet uses a WellKnownScaleSet, it shall specify it, to facilitate this backwards compatibility with WMTS?

If you find it confusing, then we definitely need to improve something :)

**Comment by cportele** [comment]
> If there isn't already, maybe there should be normative requirements that if a TileMatrixSet uses a WellKnownScaleSet, it shall specify it, to facilitate this backwards compatibility with WMTS?

I do not know why "backwards compatibility with WMTS" is important for Tiles. Is that discussed somewhere? This is OGC API Tiles, not a new version of WMTS. 

My view is that since the WKSS are no longer relevant (everything continues to work, if we remove them entirely from the spec and all encodings), we should ignore them. There could be an explanation in release notes or a guide why they have been removed and are no longer used. In any case, please do not make a redundant concept mandatory. I have removed all mentions of WKSS from our implementation during the code sprint.

I find the WKSS aspect confusing as I thought I must be missing something as all those definitions in annex C and the references to WKSS in the TMS model wouldn't be included unless the WKSS were important for something. I took a while until I decided they are just a concept that is left over from the past.

That said, since nothing changes, if the WKSS are left in the document, I am also ok with keeping them in the document, if that is considered important. As long as implementations do not have to worry about them.

**Comment by jerstlouis** [comment]
> I do not know why "backwards compatibility with WMTS" is important for Tiles. Is that discussed somewhere? This is OGC API Tiles, not a new version of WMTS.

In WMTS, there was no concept of TileMatrixSet URIs, so WKSS were the only global identifiers that could be recognized. Though _OGC API - Tiles_ is not a new version of WMTS (couldn't that be argued though? OGC API - Features was originally called WFS3), it definitely is a spiritual successor to it.

Since existing WMTS clients do not have a concept of global TileMatrixSet URIs, but do have global WKSS identifiers, the presence of a WKSS in a TileMatrixSet definition might facilitates the usability of those TileMatrixSets if they happen to use the WKSS originally defined in WMTS 1.0.0 Annex E (the same first 4 as in TMS 2.0 Annex C). This may also greatly facilitate building a WMTS facade or cascading service over an OGC API - Tiles service, for vice-versa.

> In any case, please do not make a redundant concept mandatory. I have removed all mentions of WKSS from our implementation during the code sprint.

Then maybe a recommendation that if a TileMatrixSet follows a WKSS the wellKnownScaleSet identifier should be specified is more appropriate. It really is a minimal burden for the server to just declare the WKSS that a TileMatrixSet is based on, if applicable.

>  I took a while until I decided they are just a concept that is left over from the past.

Yes, but we decided to keep them to smoothen the transition from _WMTS_ to _OGC API - Tiles_.

**Comment by joanma747** [comment]
Is anybody declaring aloud the need for WKSS. If not we will remove it!! (a WMTS facade could be an example of this).

**Comment by ghobona** [comment]
Closing this GitHub Issue because the discussion was continued and completed at https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/36#issuecomment-893564177
